version: '3'

services:
 web:
    build: ./docker-nginx
    ports:
        - 80:80
    depends_on:
        - app
    volumes:
        - ./:/var/www/html
        - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
 app:
    build: ./docker-php
    depends_on:
        - redis
    links:
        - redis
    volumes:
        - ./:/var/www/html

 redis:
    image: redis:latest
    hostname: redis
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
